name: CI/CD Laravel Production

on:
  push:
    branches: [ "main" ] # Script ini menyala otomatis setiap ada push ke branch main

jobs:
  build-and-push:
    runs-on: ubuntu-latest # Menggunakan arsitektur Intel (amd64), dijamin cocok dengan VPS Anda

    steps:
    - name: Tarik Kode
      uses: actions/checkout@v4

    - name: Login ke Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build dan Push ke Docker Hub
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/meal-planner:latest
